### ISSUE TITLE
Error: Could not find or load main class net.vzurczak.timesheetgenerator.Main

### ISSUE THREAD

**Issue by zygimantus** [vincent-zurczak/time-sheet-generator#1]
Hello, there, I have a simple question: where to put run.sh that it will find yout Main.class? 

Because I got this error: 
`Error: Could not find or load main class net.vzurczak.timesheetgenerator.Main`

**Comment by vincent-zurczak** [comment]
Hi,

I forgot to mention how to compile it in the readme.
You must use MAven.

Once you have run `mvn clean package`, there is a ZIP file under the **target** directory. Unzip it anywhere you want. It is the **run.sh** script inside this directory that must be run. It will find the class in the JAR file located in that same directory.

**Comment by zygimantus** [comment]
Yes, now I understood, thank you.
